#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/timeb.h>

int main()
{
 int i;
/* struct tm
 {
  int tm_sec;			// Seconds.	[0-60] (1 leap second)
  int tm_min;			// Minutes.	[0-59]
  int tm_hour;			// Hours.	[0-23]
  int tm_mday;			// Day.		[1-31]
  int tm_mon;			// Month.	[0-11]
  int tm_year;			// Year	- 1900.
  int tm_wday;			// Day of week.	[0-6]
  int tm_yday;			// Days in year.[0-365]
  int tm_isdst;			// DST.		[-1/0/1]
 };
 struct timeb
 {
  time_t time;			// Seconds since epoch, as from `time'.
  unsigned short int millitm;	// Additional milliseconds.
  short int timezone;		// Minutes west of GMT.
  short int dstflag;		// Nonzero if Daylight Savings Time used.
 };*/
 struct timeb *tim2=(struct timeb *)malloc(sizeof(struct timeb));
 ftime(tim2);
 tim2->time-=172800;
 struct tm tim=*(struct tm *)localtime(&(tim2->time));
 char *honap[]={"január","február","március","április","május","június","július","augusztus","szeptember","október","november","december"};
 char *nap[]={"vasárnap","hétfö","kedd","szerda","csütörtök","péntek","szombat"};
 char *jan[]={"",
 "Fruzsina",
 "Ábel",
 "Genovéva és Benjámin",
 "Titusz és Leona",
 "Simon",
 "Boldizsár",
 "Attila és Ramóna",
 "Gyöngyvér",
 "Marcell",
 "Melánia",
 "Ágota",
 "Ernõ",
 "Veronika",
 "Bódog",
 "Lóránt és Loránd",
 "Gusztáv",
 "Antal és Antónia",
 "Piroska",
 "Sára és Márió",
 "Fábián és Sebestyén",
 "Ágnes",
 "Vince és Artúr",
 "Zelma és Rajmund",
 "Timót",
 "Pál",
 "Vanda és Paula",
 "Angelika",
 "Károly és Karola",
 "Adél",
 "Martina és Gerda",
 "Marcella"};
 char fb[30][20]={"",
 "Ignác",
 "Karolina és Aida",
 "Balázs",
 "Ráhel és Csenge",
 "Ágota és Ingrid",
 "Dorottya és Dóra",
 "Tódor és Rómeó",
 "Aranka",
 "Abigél és Alex",
 "Elvira",
 "Bertold és Marietta",
 "Lívia és Lídia",
 "Ella és Linda",
 "Bálint és Valentin",
 "Kolos és Georgina",
 "Julianna és Lilla",
 "Donát",
 "Bernadett",
 "Zsuzsanna",
 "Aladár és Álmos",
 "Eleonóra",
 "Gerzson",
 "Alfréd",
 "Mátyás",
 "Géza",
 "Edina",
 "Ákos és Bátor",
 "Elemér",""};
 if (!tim.tm_year%4)
 {
  for(i=29;i>25;i--)strcpy (fb[i],fb[i-1]);
  strcpy(fb[25],"Szökönap");
 }
 char *feb[30];
 for(i=1;i<30;i++)feb[i]=fb[i];
 char *mar[]={"",
 "Albin",
 "Lujza",
 "Kornélia",
 "Kázmér",
 "Adorján és Adrián",
 "Leonóra és Inez",
 "Tamás",
 "Zoltán",
 "Franciska és Fanni",
 "Ildikó",
 "Szilárd",
 "Gergely",
 "Krisztián és Ajtony",
 "Matild",
 "Kristóf",
 "Henrietta",
 "Gertrúd és Patrik",
 "Sándor és Ede",
 "József és Bánk",
 "Klaudia",
 "Benedek",
 "Beáta és Izolda",
 "Emõke",
 "Gábor és Karina",
 "Irén és Irisz",
 "Emánuel",
 "Hajnalka",
 "Gedeon és Johanna",
 "Aguszta",
 "Zalán",
 "Árpád"};
 char *apr[]={"",
 "Hugó",
 "Áron",
 "Buda és Richárd",
 "Izidor",
 "Vince",
 "Vilmos és Bíborka",
 "Herman",
 "Dénes",
 "Erhard",
 "Zsolt",
 "Leó és Szaniszló",
 "Gyula",
 "Ida",
 "Tibor",
 "Anasztázia és Tas",
 "Csongor",
 "Rudolf",
 "Andrea és Ilma",
 "Emma",
 "Tivadar",
 "Konrád",
 "Csilla és Noémi",
 "Béla",
 "György",
 "Márk",
 "Ervin",
 "Zita",
 "Valéria",
 "Péter",
 "Katalin és Kitti"};
 char *maj[]={"",
 "Fülöp és Jakab",
 "Zsigmond",
 "Tímea és Irma",
 "Mónika és Flórián",
 "Györgyi",
 "Ivett és Frida",
 "Gizella",
 "Mihály",
 "Gergely",
 "Ármin és Pálma",
 "Ferenc",
 "Pongrác",
 "Szervác és Imola",
 "Bonifác",
 "Zsófia és Szonja",
 "Mózes és Botond",
 "Paszkál",
 "Erik és Alexandra",
 "Ivó és Milán",
 "Bernát és Felícia",
 "Konstantin",
 "Júlia és Rita",
 "Dezsõ",
 "Eszter és Eliza",
 "Orbán",
 "Fülöp és Evelin",
 "Hella",
 "Emil és Csanád",
 "Magdolna",
 "Janka és Zsanett",
 "Angéla és Petronella"};
 char *jun[]={"",
 "Tünde",
 "Kármen és Anita",
 "Klotild",
 "Bulcsú",
 "Fatime",
 "Norbert és Cintia",
 "Róbert",
 "Medárd",
 "Félix",
 "Margit és Gréta",
 "Barnabás",
 "Villõ",
 "Antal és Anett",
 "Vazul",
 "Jolán és Vid",
 "Jusztin",
 "Laura és Alida",
 "Arnold és Levente",
 "Gyárfás",
 "Rafael",
 "Alajos és Leila",
 "Paulina",
 "Zoltán",
 "Iván",
 "Vilmos",
 "János és Pál",
 "László",
 "Levente és Irén",
 "Péter és Pál",
 "Pál"};
 char *jul[]={"",
 "Tihamér és Annamária",
 "Ottó",
 "Kornél és Soma",
 "Ulrik",
 "Emese és Sarolta",
 "Csaba",
 "Apollónia",
 "Ellák",
 "Lukrécia",
 "Amália",
 "Nóra és Lili",
 "Izabella és Dalma",
 "Jenõ",
 "Örs és Stella",
 "Henrik és Roland",
 "Valter",
 "Endre és Elek",
 "Frigyes",
 "Emília",
 "Illés",
 "Dániel és Daniella",
 "Magdolna",
 "Lenke",
 "Kinga és Kincsõ",
 "Kristóf és Jakab",
 "Anna és Anikó",
 "Olga és Liliána",
 "Szabolcs",
 "Márta és Flóra",
 "Judit és Xénia",
 "Oszkár"};
 char *aug[]={"",
 "Boglárka",
 "Lehel",
 "Hermina",
 "Domonkos és Dominika",
 "Krisztina",
 "Berta és Bettina",
 "Ibolya",
 "László",
 "Emõd",
 "Lõrinc",
 "Zsuzsanna és Tiborc",
 "Klára",
 "Ipoly",
 "Marcell",
 "Mária",
 "Ábrahám",
 "Jácint",
 "Ilona",
 "Huba",
 "István",
 "Sámuel és Hajna",
 "Menyhért és Mirjam",
 "Bence",
 "Bertalan",
 "Lajos és Patrícia",
 "Izsó",
 "Gáspár",
 "Ágoston",
 "Beatrix és Erna",
 "Rózsa",
 "Erika és Bella"};
 char *sep[]={"",
 "Egyed és Egon",
 "Rebeka és Dorina",
 "Hilda",
 "Rozália",
 "Viktor és Lõrinc",
 "Zakariás",
 "Regina",
 "Mária és Adrienn",
 "Ádám",
 "Nikolett és Hunor",
 "Teodóra",
 "Mária",
 "Kornél",
 "Szeréna és Roxána",
 "Enikõ és Melitta",
 "Edit",
 "Zsófia",
 "Diána",
 "Vilhelmina",
 "Friderika",
 "Máté és Mirella",
 "Móric",
 "Tekla",
 "Gellért és Mercédesz",
 "Eufrozina és Kende",
 "Jusztina",
 "Adalbert",
 "Vencel",
 "Mihály",
 "Jeromos"};
 char *okt[]={"",
 "Malvin",
 "Petra",
 "Helga",
 "Ferenc",
 "Aurél",
 "Brúnó és Renáta",
 "Amália",
 "Koppány",
 "Dénes",
 "Gedeon",
 "Brigitta",
 "Miksa",
 "Kálmán és Ede",
 "Helén",
 "Teréz",
 "Gál",
 "Hedvig",
 "Lukács",
 "Nándor",
 "Vendel",
 "Orsolya",
 "Elõd",
 "Gyöngyi",
 "Salamon",
 "Blanka és Bianka",
 "Dömötör",
 "Szabina",
 "Simon és Szimonetta",
 "Nárcisz",
 "Alfonz",
 "Farkas"};
 char *nov[]={"",
 "Marianna",
 "Achilles",
 "Gyõzõ",
 "Károly",
 "Imre",
 "Lénárd",
 "Rezsõ",
 "Zsombor",
 "Tivadar",
 "Réka",
 "Márton",
 "Jónás és Renátó",
 "Szilvia",
 "Aliz",
 "Albert és Lipót",
 "Ödön",
 "Hortenzia és Gergõ",
 "Jenõ",
 "Erzsébet",
 "Jolán",
 "Olivér",
 "Cecília",
 "Kelemen és Klementina",
 "Emma",
 "Katalin",
 "Virág",
 "Virgil",
 "Stefánia",
 "Taksony",
 "András és Andor"};
 char *dec[]={"",
 "Elza",
 "Melinda és Vivien",
 "Ferenc",
 "Borbála és Barbara",
 "Vilma",
 "Miklós",
 "Ambrus",
 "Mária",
 "Natália",
 "Judit",
 "Árpád",
 "Gabriella",
 "Luca és Otília",
 "Szilárda",
 "Valér",
 "Etelka és Aletta",
 "Lázár és Olimpia",
 "Auguszta",
 "Viola",
 "Teofil",
 "Tamás",
 "Zénó",
 "Viktória",
 "Ádám és Éva",
 "Eugénia",
 "István",
 "János",
 "Kamilla",
 "Tamás és Tamara",
 "Dávid",
 "Szilveszter"};
 char **nevnap[]={jan,feb,mar,apr,maj,jun,jul,aug,sep,okt,nov,dec};
 printf("                                %s\n",nevnap[tim.tm_mon][tim.tm_mday]);
 tim2->time+=86400;tim=*(struct tm *)localtime(&(tim2->time));
 printf("                                %s\n",nevnap[tim.tm_mon][tim.tm_mday]);
 tim2->time+=86400;tim=*(struct tm *)localtime(&(tim2->time));
 for(i=0;i<19-strlen(honap[tim.tm_mon])-strlen(nap[tim.tm_wday]);i++)printf(" ");
 printf("%d. %s %2d. %s, %s napja\n",tim.tm_year+1900,honap[tim.tm_mon],tim.tm_mday,nap[tim.tm_wday],nevnap[tim.tm_mon][tim.tm_mday]);
 tim2->time+=86400;tim=*(struct tm *)localtime(&(tim2->time));
 printf("                                %s\n",nevnap[tim.tm_mon][tim.tm_mday]);
 tim2->time+=86400;tim=*(struct tm *)localtime(&(tim2->time));
 printf("                                %s\n",nevnap[tim.tm_mon][tim.tm_mday]);
 tim2->time+=86400;tim=*(struct tm *)localtime(&(tim2->time));
 printf("                                %s\n",nevnap[tim.tm_mon][tim.tm_mday]);
 tim2->time+=86400;tim=*(struct tm *)localtime(&(tim2->time));
 printf("                                %s\n",nevnap[tim.tm_mon][tim.tm_mday]);
 tim2->time+=86400;tim=*(struct tm *)localtime(&(tim2->time));
 printf("                                %s\n",nevnap[tim.tm_mon][tim.tm_mday]);
 return(0);
}
