#!/bin/bash

PSU_CNT=6
if [ "$1" == "201" ]; then
    PSU_IP1=163.33.145.22
    shift
elif [ "$1" == "202" ]; then
    PSU_IP1=163.33.145.28
    shift
elif [ "$1" == "203" ]; then
    PSU_IP1=163.33.145.34
    shift
elif [ "$1" == "204" ]; then
    PSU_IP1=163.33.145.40
    shift
elif [ "$1" == "205" ]; then
    PSU_IP1=163.33.145.46
    shift
else
    PSU_IP1=163.33.145.22
fi



PSU_IPROOT=`cut -d '.' -f 1-3 <<< $PSU_IP1`
PSU_IPLAST=`cut -d '.' -f 4 <<< $PSU_IP1`
if [ "$1" == "on" ]; then
    for i in `seq $PSU_IPLAST $(($PSU_IPLAST + $PSU_CNT - 1))`; do
        echo "OUTP:GEN ON" | nc -q1 $PSU_IPROOT.$i 5025 &
    done
elif [ "$1" == "off" ]; then
    for i in `seq $PSU_IPLAST $(($PSU_IPLAST + $PSU_CNT - 1))`; do
        echo "OUTP:GEN OFF" | nc -q1 $PSU_IPROOT.$i 5025 &
    done
else
    echo "Hamegs @ rig20x, Usage: $0 [(201)|202|...|205] <on|off>" 1>&2
fi
