#!/bin/bash

if [ $# -lt 2 ] || [ `wc -c <<< $@` -lt 380 ] || ! grep -iq '[rd]sa' <<< $1 || ! grep -q '^[A-Za-z0-9+/]\+=*$' <<< $2; then
	echo "Error: not a valid key. Expected format: 'ssh-rsa <ssh key> [user@host]'" 1>&2
	echo "$@" 1>&2
	exit 1
fi
mkdir .ssh 2>/dev/null && chmod 700 .ssh && touch .ssh/authorized_keys && chmod 600 .ssh/authorized_keys
echo "no-agent-forwarding,no-port-forwarding,no-X11-forwarding $@" >> .ssh/authorized_keys
logger -t git.add-key -p daemon.notice "Added SSH key for $3 $1 $2"
