#!/bin/bash

if [ $# -lt 2 ] || [ `wc -c <<< $@` -lt 380 ] || ! grep -iq '[rd]sa' <<< $1 || ! grep -q '^[A-Za-z0-9+/]\+=*$' <<< $2; then
	echo "Error: not a valid key. Expected format: 'ssh-dsa <ssh key>'" 1>&2
	echo "$@" 1>&2
	exit 1
fi
mkdir .ssh 2>/dev/null && chown 700 .ssh && touch .ssh/authorized_keys && chmod 600 .ssh/authorized_keys
echo -n "no-agent-forwarding,no-port-forwarding,no-X11-forwarding $@" >> .ssh/authorized_keys
