#!/bin/sh

mkdir /var/lock/shmtool || exit 1
TGZFILE=/var/tmp/shm.tgz
IFS='
'

if [ "$1" == "start" ]; then
	[ -e /dev/shm/permanent/done ] && rmdir /var/lock/shmtool && exit 2
	mkdir -p /dev/shm/permanent/ /dev/shm/tmp/
	chmod 1777 /dev/shm/permanent/ /dev/shm/tmp/
	if unpigz < ${TGZFILE} | tar x -C /dev/shm/permanent/; then
		touch /dev/shm/permanent/done
	else
		if unpigz < ${TGZFILE}~ | tar x --overwrite -C /dev/shm/permanent/; then
			/usr/bin/logger -t shmtool -p warning "Warning: backup image used"
			touch /dev/shm/permanent/done
		else
			/usr/bin/logger -t shmtool -p err "Image decompression failed"
			rmdir /var/lock/shmtool && exit 3
		fi
	fi
elif [ "$1" == "stop" -o "$1" == "save" ]; then
	rm /dev/shm/permanent/done
	pigz -t < ${TGZFILE} && mv ${TGZFILE} ${TGZFILE}~
	tar c -C /dev/shm/permanent `ls -1 /dev/shm/permanent` | pigz > ${TGZFILE}
	[ "$1" == "save" ] && touch /dev/shm/permanent/done
fi
rmdir /var/lock/shmtool
