#!/bin/sh

DELAY="0.8"

if 3dsw test; then
  if [ -z "`ps ax | grep [3]ddeskd`" ]; then
    3ddeskd --wm=fluxbox
  fi
#  if [ -z "`ps ax | grep [x]screensaver`" ]; then
#    nice xscreensaver -nosplash &
#  fi
fi

nice wmbatteries >/dev/null 2>/dev/null &
nice ascpu -withdrawn -bg "#000000" -user "#546920" -sys "#803304" -nice "#166883" > /dev/null 2>/dev/null &
#rm -f $HOME/.mozilla/firefox/*default/sessionstore.js > /dev/null 2>&1
#aterm -C -title Aterm1 +ut +sb -fn -misc-fixed-bold-*-*-*-14-*-*-*-*-*-iso8859-2 -ls -sl 300 -fg green -tr -sh 50 &
urxvt -C -title AlsaMixer -e alsamixer &
firefox &
sleep ${DELAY}
#aterm -C -title MC +ut +sb -fn -misc-fixed-bold-*-*-*-14-*-*-*-*-*-iso8859-2 -ls -sl 300 -fg green -tr -sh 50 -e mc &
urxvt -C -title MC -e mc &
xmms &
sleep ${DELAY}
#aterm -C -title Aterm2 +ut +sb -fn -misc-fixed-bold-*-*-*-14-*-*-*-*-*-iso8859-2 -ls -sl 300 -fg green -tr -sh 50 &
urxvt -C -title Aterm2 &
thunderbird &
sleep ${DELAY}
#aterm -C -title MC +ut +sb -fn -misc-fixed-bold-*-*-*-14-*-*-*-*-*-iso8859-2 -ls -sl 300 -fg green -tr -sh 50 -e mc &
urxvt -C -title MC -e mc &
apulse skype &
sleep ${DELAY}
#aterm -C -title Aterm3 +ut +sb -fn -misc-fixed-bold-*-*-*-14-*-*-*-*-*-iso8859-2 -ls -sl 300 -fg green -tr -sh 50 &
urxvt -C -title Aterm3 &

wmctrl -s 3

if 3dsw test; then
  sleep 10
  3ddesk --acquire=10
fi
