#!/bin/sh

if [ -x /etc/conf.d/cpufreq ]; then
    /etc/conf.d/cpufreq stop > /dev/null
fi

sleep 40

if [ -x /etc/conf.d/cpufreq ]; then
    /etc/conf.d/cpufreq start > /dev/null
fi

killall fbstart plugin-container `basename "$0"`
