#!/bin/sh

# Script for ease of installing scripts to their respective places from this repo
[ -z "$1" ] && echo "Usage: scinst <script-in-repo>" && exit 1
[ "`id -u`" != "0" ] && echo "Error: you need to be root to run scinst" && exit 2
while [ $# -gt 0 ]; do
	[ ! -e "$1" ] && echo "Error: file '$1' not found" && exit 3
	DIR="`dirname $1`"
	[ "$DIR" == "." ] && DIR="$PWD"
	! grep -q '^/' <<< $DIR && DIR="$PWD/$DIR"
	! grep -q "scripts" <<< $DIR && echo "Error: trying to install '$1' from outside repo" && exit 4
	DIR="`sed 's/.*scripts//' <<< $DIR`"
	[ -e "$DIR" ] || mkdir -vp "$DIR"
	if [ -x "$1" ]; then
		install -v "$1" "$DIR"
	else
		install -v -m 644 "$1" "$DIR"
	fi
	shift
done
